name: CD
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Publish zfi-macros
      run: cargo publish -p zfi-macros
    - name: Publish zfi-testing-macros
      run: cargo publish -p zfi-testing-macros
    - name: Publish zfi-testing
      run: cargo publish -p zfi-testing
    - name: Publish zfi
      run: cargo publish
