name: Publish (zfi-testing)
on:
  push:
    tags:
    - 'testing-v*'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Publish
      run: cargo publish -p zfi-testing
